### ISSUE TITLE
Making an unordered unreliable datachannel doesn't seem possible

### ISSUE THREAD

**Issue by echeese** [webrtc-rs/webrtc#371] opened 2022-12-16 23:11 UTC
Creating a datachannel with `ordered = false` and (`max_retransmits = 0` or `max_packet_lifetime = 0`) seems to fall back to making a reliable channel.

The receiving other client has `maxPacketLifeTime: null` and `maxRetransmits: null`

**Comment by k0nserv** [comment] 2023-01-04 11:57
Hey @echeese, could you provide a minimal reproducible example of this? I probably won't have time to work on it but if it is indeed a bug having such an example would be good

**Comment by k0nserv** [comment] 2023-01-09 16:40
@echeese Looking at https://github.com/webrtc-rs/webrtc/pull/186 and https://github.com/webrtc-rs/data/pull/5 I think you are just correct. No need to create a minimal repro.

Someone who's interested in this could ressurect the PRs from @connorcarpenter

**Comment by echeese** [comment] 2023-01-09 16:43
Sorry for the lack of response, I was on vacation, but yes those PRs seem to match my findings

**Comment by k0nserv** [comment] 2023-01-09 16:57
No problem, if you wanna work on this it'd be great. I wouldn't expect it to get fixed unless someone with a desire for the use-case contributes a fix

**Comment by zduny** [comment] 2023-01-17 18:22
I have something: https://github.com/zduny/webrtc/commit/8a9138cfd1ddf5c1b32a9579f0033cb4768fa4d5

References:
https://github.com/pion/webrtc/blob/master/datachannel.go
https://stackoverflow.com/questions/54292824/webrtc-channel-reliability

But it would be nice to add a test checking if unreliable channel is created.
@echeese - what was your method of checking if created channel is unreliable?

**Comment by CouleeApps** [comment] 2023-10-29 16:36
What's the status on this? It seems like that PR was closed after submodule changes and was never actually merged. If needed, I can remake them, since it seems like nobody else actually cares about this use-case... strange considering the various rust game engines basing their netcode on this library without actually ... trying it.

**Comment by ris-work** [comment] 2024-02-28 17:25
I do care; I don't care about reliability as I will be doing TCP _inside_ WebRTC for my use case _if I really need it_. I have also created a set of patches (in my profile) which tries to disable _all forms of reliability for the packets_ and _all forms of congestion control_ and _stats collection_, if you're interested. It has made it lighter, too.

Also a surprising observation: Tokio Mutexes and Semaphores are surprisingly too slow, so I switched some things to _native threads_, it made it work like 100x faster. Last time a performance bottleneck was fixed by just removing `tokio` semaphores and it made things magically 3x faster.

**Closed** 2024-09-07 18:46 UTC
Labels: enhancement, subcrate:data
